SHELL = /bin/bash
CC = gcc
CXX = nvcc
DEBUGFLAGS =
FLAGS =  -I/opt/cuda/include -L/opt/cuda/lib64
CFLAGS =  #--std=c++11
CUDAFLAGS = -Xcompiler -fPIC -Xcompiler -static -arch=sm_75
RELEASEFLAGS =
LDFLAGS = -shared
TARGETFLAGS = #--output-directory $(TARGETDIR)
OBJTARFLAGS = #--output-directory $(BUILDDIR)$(OBJDIR)
GCCFLAGS =
EXTRA_CUDA_FLAGS = -fPIC
FINAL_CUDA_FLAGS = -L/usr/local/cuda/lib64 -lcudart

SOURCES = tensorplus.c
CUSOURCES = tensor.cu
HEADERS = defines.h includes.h
OBJECTS = tensorplus.o
CUOBJS = tensor.o
TARGET = tensorplus.so
TARGETMAC = tensorplus.dylib
TARGETWIN = tensorplus.dll

RM= rm -f
CP= cp -f
CMD= bash
BUILDSCRIPT= build.sh
.PHONY: clean
TARGETDIR = bin/
SOURCEDIR = lib/
BUILDDIR = build/
OBJDIR = objects/
MAKEDIRS = mkdir -p 
INSTALLDIR = src/tensorplus/

all: $(TARGET) #$(TARGETDIR)$(TARGETMAC) $(TARGETDIR)$(TARGETWIN)

#$(TARGETDIR)$(TARGETMAC): $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS)
#	$(CC) $(CFLAGS) $(EXTRA_CUDA_FLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) -o $(TARGETDIR)$(TARGETMAC) $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS) $(FLAGS) 

#$(TARGETDIR)$(TARGETWIN): $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS)
#	$(CC) $(CFLAGS) $(EXTRA_CUDA_FLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS)   -o $(TARGETDIR)$(TARGETWIN) $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS) $(FLAGS) 

$(TARGET): $(OBJECTS) $(CUOBJS)
	$(CC) $(CFLAGS) $(EXTRA_CUDA_FLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) -o $(TARGET) $(OBJECTS) $(CUOBJS) $(FLAGS) $(FINAL_CUDA_FLAGS)

$(CUOBJS): $(SOURCEDIR)$(CUSOURCES)
	$(CXX) $(CFLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) $(OBJTARFLAGS) $(CUDAFLAGS) -c $(SOURCEDIR)$(CUSOURCES) $(FLAGS)

$(OBJECTS): $(SOURCEDIR)$(SOURCES)
	$(CC) $(CFLAGS) $(EXTRA_CUDA_FLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) $(OBJTARFLAGS) -c $(SOURCEDIR)$(SOURCES) $(FLAGS)

clean:
	$(RM) $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS) $(TARGETDIR)$(TARGET) $(TARGETDIR)$(TARGETMAC) $(TARGETDIR)$(TARGETWIN) $(OBJECTS) $(CUOBJS)

#install:
	#$(CP) $(TARGETDIR)$(TARGET) $(INSTALLDIR)$(TARGET)
	#$(CP) $(TARGETDIR)$(TARGETMAC) $(INSTALLDIR)$(TARGETMAC)
	#$(CP) $(TARGETDIR)$(TARGETWIN) $(INSTALLDIR)$(TARGETWIN)
	#$(CMD) $(BUILDSCRIPT)
