SHELL = /bin/bash
CC = gcc
CXX = nvcc
DEBUGFLAGS =
FLAGS = -Iinclude -L/usr/local/cuda/lib64
CFLAGS =
CUDAFLAGS = -arch=sm_61 -Xcompiler '-fPIC'
RELEASEFLAGS =
LDFLAGS = -shared
TARGETFLAGS = --output-directory $(BUILDDIR)
OBJTARFLAGS = --output-directory $(BUILDDIR)$(OBJDIR)
GCCFLAGS =

SOURCES = tensorplus.c
CUSOURCES = tensor.cu
HEADERS = defines.h includes.h
OBJECTS = tensorplus.o
CUOBJS = tensor.o
TARGET = tensorplus.so

RM= rm -f
.PHONY: clean
SOURCEDIR = src/
BUILDDIR = build/
OBJDIR = objects/

$(BUILDDIR)$(TARGET): $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS)
	$(CXX) $(FLAGS) $(CFLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) $(CUDAFLAGS) -o $(BUILDDIR)$(TARGET) $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS)

$(BUILDDIR)$(OBJDIR)$(CUOBJS): $(SOURCEDIR)$(CUSOURCES)
	$(CXX) $(FLAGS) $(CFLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) $(OBJTARFLAGS) $(CUDAFLAGS) -c $(SOURCEDIR)$(CUSOURCES)

$(BUILDDIR)$(OBJDIR)$(OBJECTS): $(SOURCEDIR)$(SOURCES)
	$(CXX) $(FLAGS) $(CFLAGS) $(DEBUGFLAGS) $(LDFLAGS) $(GCCFLAGS) $(OBJTARFLAGS) $(CUDAFLAGS) -c $(SOURCEDIR)$(SOURCES)

clean:
	$(RM) $(BUILDDIR)$(OBJDIR)$(OBJECTS) $(BUILDDIR)$(OBJDIR)$(CUOBJS) $(BUILDDIR)$(TARGET)