#pragma once
#include "cuda_runtime.h"
#include <stdio.h>

struct Tensor {};
void print_tensor(void);
void fill(void);
void add(void);
void sub(void);
void mul(void);
void div(void);
void add_scalar(void);
void sub_scalar(void);
void mul_scalar(void);
void div_scalar(void);
void dot(void);
void transpose(void);
void sum(void);
void mean(void);
void max(void);
void min(void);
void abs(void);
void exp(void);
void log(void);
void sqrt(void);
void pow(void);
void sin(void);
void cos(void);
void tan(void);
void asin(void);
void acos(void);
void atan(void);
void sinh(void);
void cosh(void);
void tanh(void);
void asinh(void);
void acosh(void);
void atanh(void);
void gradient(void);
void gate(void);